-- MySQL Script generated by MySQL Workbench
-- Tue 16 May 2017 02:38:04 PM BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NULL,
  `numero` INT NULL,
  `cidade` VARCHAR(45) NULL,
  `UF` VARCHAR(2) NULL,
  `cep` INT(8) NULL,
  PRIMARY KEY (`idendereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `idpessoas` INT NOT NULL AUTO_INCREMENT,
  `cpf` INT(11) NULL,
  `telefone` INT(9) NULL,
  `email` VARCHAR(45) NULL,
  `nomecompleto` VARCHAR(60) NULL,
  `endereco_idendereco` INT NOT NULL,
  PRIMARY KEY (`idpessoas`),
  INDEX `fk_pessoas_endereco1_idx` (`endereco_idendereco` ASC),
  CONSTRAINT `fk_pessoas_endereco1`
    FOREIGN KEY (`endereco_idendereco`)
    REFERENCES `mydb`.`Endereco` (`idendereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idusuarios` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `pessoas_idpessoas` INT NOT NULL,
  `tipousuarios` INT NULL,
  PRIMARY KEY (`idusuarios`),
  INDEX `fk_usuarios_pessoas1_idx` (`pessoas_idpessoas` ASC),
  CONSTRAINT `fk_usuarios_pessoas1`
    FOREIGN KEY (`pessoas_idpessoas`)
    REFERENCES `mydb`.`Pessoa` (`idpessoas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Turma` (
  `nome` VARCHAR(45) NULL,
  `idturma` INT NOT NULL,
  `turno` VARCHAR(15) NULL,
  `usuarios_idusuarios` INT NOT NULL,
  `numerosala` INT NULL,
  INDEX `fk_turma_usuarios1_idx` (`usuarios_idusuarios` ASC),
  PRIMARY KEY (`idturma`),
  CONSTRAINT `fk_turma_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `mydb`.`Usuario` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluno` (
  `matricula` INT NOT NULL,
  `usuarios_idusuarios` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_alunos_usuarios1_idx` (`usuarios_idusuarios` ASC),
  CONSTRAINT `fk_alunos_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `mydb`.`Usuario` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professores` (
  `idprofessores` INT NOT NULL,
  `disciplina` VARCHAR(45) NULL,
  `usuarios_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idprofessores`),
  INDEX `fk_professores_usuarios1_idx` (`usuarios_idusuarios` ASC),
  CONSTRAINT `fk_professores_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `mydb`.`Usuario` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Responsavel` (
  `idresponsavel` INT NOT NULL AUTO_INCREMENT,
  `alunos_matricula` INT NOT NULL,
  `usuarios_idusuarios` INT NOT NULL,
  PRIMARY KEY (`idresponsavel`),
  INDEX `fk_responsavel_alunos1_idx` (`alunos_matricula` ASC),
  INDEX `fk_responsavel_usuarios1_idx` (`usuarios_idusuarios` ASC),
  CONSTRAINT `fk_responsavel_alunos1`
    FOREIGN KEY (`alunos_matricula`)
    REFERENCES `mydb`.`Aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_responsavel_usuarios1`
    FOREIGN KEY (`usuarios_idusuarios`)
    REFERENCES `mydb`.`Usuario` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`RelatórioParental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`RelatorioParental` (
  `idRelatorioParental` INT NOT NULL AUTO_INCREMENT,
  `observacoes` VARCHAR(300) NULL,
  `comportamento` FLOAT NULL,
  `participacao_em_aula` FLOAT NULL,
  `facilidade_com_disciplina` FLOAT NULL,
  `trabalho_em_equipe` FLOAT NULL,
  `lideranca` FLOAT NULL,
  `motivacao` FLOAT NULL,
  `criatividade` FLOAT NULL,
  `alunos_matricula` INT NOT NULL,
  `professores_idprofessores` INT NOT NULL,
  `responsavel_idresponsavel` INT NOT NULL,
  PRIMARY KEY (`idRelatorioParental`),
  INDEX `fk_RelatorioParental_alunos1_idx` (`alunos_matricula` ASC),
  INDEX `fk_RelatorioParental_professores1_idx` (`professores_idprofessores` ASC),
  INDEX `fk_RelatorioParental_responsavel1_idx` (`responsavel_idresponsavel` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = big5;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;